### ISSUE TITLE
docker-commons Plugin Fails to Build Image

### ISSUE THREAD

**Issue by kudla** [agilestacks/jenkins#6]
Using `docker-plugin` as follows
```
docker.withRegistry(registryServer, 'creds-secret') {
        def customImage = docker.build("${image}:${gitscm.shortCommit}")

        /* Push the container to the custom Registry */
        customImage.push()
}
```
leads `docker-commons` fails on the instruction
```
docker.build(...
``` 
while resolving build hash
```
java.lang.IllegalArgumentException: Expecting 64-char full image ID, but got Docker daemon is not running! Starting...
sha256:491e0ff7a8d51cd66a07e8b98976694174e82c0abbc77a96533c580a11378464
	at org.jenkinsci.plugins.docker.commons.fingerprint.DockerFingerprints.getFingerprintHash(DockerFingerprints.java:71)
	at org.jenkinsci.plugins.docker.commons.fingerprint.DockerFingerprints.forDockerInstance(DockerFingerprints.java:147)
	at org.jenkinsci.plugins.docker.commons.fingerprint.DockerFingerprints.forImage(DockerFingerprints.java:114)
	at org.jenkinsci.plugins.docker.commons.fingerprint.DockerFingerprints.forImage(DockerFingerprints.java:99)
	at org.jenkinsci.plugins.docker.commons.fingerprint.DockerFingerprints.addFromFacet(DockerFingerprints.java:259)
	at org.jenkinsci.plugins.docker.workflow.FromFingerprintStep$Execution.run(FromFingerprintStep.java:133)
	at org.jenkinsci.plugins.docker.workflow.FromFingerprintStep$Execution.run(FromFingerprintStep.java:85)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
It is not clear whether it `sha256:` prefix or log `Docker daemon is not...` is the exact cause. But according to this [commit](https://github.com/jenkinsci/docker-commons-plugin/commit/8d947ca5e2203fb43d92cf6ddb6b9464a153da50) version  `1.13` should handle `sha256:` prefix well.

Anyway for now as a workaround continue to use `docker-plugin` only for authorization purpose with `docker.withRegistry()` and direct docker shell command calls which works well.

**Comment by akranga** [comment]
Oho, are you running it from toolbox?

**Comment by kudla** [comment]
yes

**Comment by akranga** [comment]
Then let's see what we can do about that

**Comment by akranga** [comment]
Found guilty https://github.com/agilestacks/toolbox/blob/master/etc/docker
